import Navbar from "@/components/comp/Navbar";
import AllProviders from "@/globalProviders/AllProviders";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AllProviders>
          <Toaster position="top-center" richColors />
          <Navbar />
          {children}
        </AllProviders>
      </body>
    </html>
  );
}
